spring:
  application:
    name: SBMSWithProcedures
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/sbms
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
